{{- if .Values.common.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dlw.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.common.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dlw.fullname" . }}-executor
  namespace: {{ .Release.Namespace }}
{{- end }}
