"""initial v2 schema

Revision ID: bce7fa21af9c
Revises: 
Create Date: 2026-05-07 17:02:07.626386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce7fa21af9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_ip', postgresql.INET(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('self_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('quota_bytes_month', sa.BigInteger(), nullable=False),
    sa.Column('quota_concurrent', sa.BigInteger(), nullable=False),
    sa.Column('quota_storage_gb', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('executors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('host_id', sa.String(length=64), nullable=False),
    sa.Column('parent_executor_id', sa.String(length=64), nullable=True),
    sa.Column('cert_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('health_score', sa.SmallInteger(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_heartbeat_failures', sa.Integer(), nullable=False),
    sa.Column('consecutive_task_failures', sa.Integer(), nullable=False),
    sa.Column('degraded_failure_streak', sa.Integer(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nic_speed_gbps', sa.SmallInteger(), nullable=True),
    sa.Column('disk_free_gb', sa.BigInteger(), nullable=True),
    sa.Column('disk_total_gb', sa.BigInteger(), nullable=True),
    sa.Column('parts_dir_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_executors_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_executors'))
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('storage_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_projects_tenant_id'))
    )
    op.create_table('storage_backends',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('backend_type', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_storage_backends_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_backends')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_storage_backends_tenant_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('oidc_subject', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('oidc_subject', name=op.f('uq_users_oidc_subject'))
    )
    op.create_table('download_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.String(length=256), nullable=False),
    sa.Column('revision', sa.String(length=64), nullable=False),
    sa.Column('storage_id', sa.BigInteger(), nullable=False),
    sa.Column('path_template', sa.String(length=512), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('download_bytes_limit', sa.BigInteger(), nullable=True),
    sa.Column('upgrade_from_revision', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_download_tasks_owner_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_download_tasks_project_id_projects')),
    sa.ForeignKeyConstraint(['storage_id'], ['storage_backends.id'], name=op.f('fk_download_tasks_storage_id_storage_backends')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_download_tasks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_tasks'))
    )
    op.create_table('file_subtasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('expected_sha256', sa.String(length=64), nullable=True),
    sa.Column('actual_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executor_id', sa.String(length=64), nullable=True),
    sa.Column('executor_epoch', sa.BigInteger(), nullable=True),
    sa.Column('assignment_token', sa.UUID(), nullable=True),
    sa.Column('chunks_total', sa.Integer(), nullable=True),
    sa.Column('chunks_completed', sa.Integer(), nullable=False),
    sa.Column('bytes_downloaded', sa.BigInteger(), nullable=False),
    sa.Column('multipart_upload_id', sa.String(length=256), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['download_tasks.id'], name=op.f('fk_file_subtasks_task_id_download_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_subtasks')),
    sa.UniqueConstraint('task_id', 'filename', name=op.f('uq_file_subtasks_task_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_subtasks')
    op.drop_table('download_tasks')
    op.drop_table('users')
    op.drop_table('storage_backends')
    op.drop_table('projects')
    op.drop_table('executors')
    op.drop_table('tenants')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
