[request_definition]
r = sub, tenant, obj, act, rtenant

[policy_definition]
p = sub, obj, act, scope

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act) && (p.scope == "any" || r.tenant == r.rtenant)
